language: node_js
sudo: required
services:
  - docker
notifications:
  email: false
node_js:
  - '10'
install:
  - npm ci
jobs:
  include:
  - stage: Lint
    script: npm run lint
  - stage: Test
    script: npm run test && npx codecov
  - stage: Deploy
    script: npm run deploy && curl -sSL https://raw.githubusercontent.com/RedHatInsights/insights-frontend-builder-common/master/src/bootstrap.sh | bash -s
  - stage: Build
    script: "docker build -t benthomasson/tower-analytics-frontend:${BRANCH} ."
  #- stage: Push (disabled until full integration testing is created)
  #  script: bash docker_push
env:
    global:
    - REPO="git@github.com:RedHatInsights/tower-analytics-frontend-build.git"
    - REPO_DIR="tower-analytics-frontend-build"
    - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
    - NODE_OPTIONS="--max-old-space-size=4096 --max_old_space_size=4096"
