branches:
  only:
  - devel
  - prod-stable

language: node_js
sudo: required
services:
  - docker
notifications:
  email: false
node_js:
  - '15'
install:
  - npm ci
jobs:
  include:
  - stage: PR Check
    script: npm run deploy-only && curl -sSL https://raw.githubusercontent.com/jameswnl/insights-frontend-builder-common/master/src/bootstrap.sh | bash -s
env:
    global:
    - REPO="git@github.com:RedHatInsights/tower-analytics-frontend-build.git"
    - REPO_DIR="tower-analytics-frontend-build"
    - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
    - NODE_OPTIONS="--max-old-space-size=4096 --max_old_space_size=4096"
    - PR_CHECK=true
