export const actions = {
  SET_NAME: 'SET_NAME',
  SET_CATEGORY: 'SET_CATEGORY',
  SET_DESCRIPTION: 'SET_DESCRIPTION',
  SET_MANUAL_TIME: 'SET_MANUAL_TIME',
  SET_HOSTS: 'SET_HOSTS',
  SET_FREQUENCY_PERIOD: 'SET_FREQUENCY_PERIOD',
  SET_TASKS: 'SET_TASKS',
  SET_TEMPLATE_ID: 'SET_TEMPLATE_ID',
};
